#!/bin/sh

MODDIR=/lib/modules
boxtype=`cat /etc/boxtype`

if [ $boxtype == 'bska' ]; then
  echo "Init VFD bialy"
  insmod $MODDIR/vfd.ko rec=0
else
  echo "Init VFD czarny"
  insmod $MODDIR/vfd.ko rec=1
fi

if [ -e /var/etc/.firstboot ]; then
   #fp_control does not work here
   echo "WAIT 1 min" >/dev/vfd
   echo "WAIT 1 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start

/etc/init.d/portmap start

    insmod $MODDIR/boxtype.ko
    boxtype=`cat /proc/boxtype`
    echo "boxtype $boxtype"
    echo "$boxtype" > /etc/boxtype

insmod $MODDIR/e2_proc.ko

/etc/init.d/autofs start

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   NFS=`grep -c nfs /proc/cmdline`
   if [ "$NFS" -eq "1" ]; then
      # We can not correct the mac from userspace if we are booting from nfsroot
      echo "Booting from nfs, don't set network"
   else
      HWADDR=`strings /dev/mtdblock2 | tail -n 1`
      ifconfig eth0 down
      ifconfig eth0 hw ether ${HWADDR}
      ifconfig eth0 up
   fi

   fp_control -c

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-stx7100.ko
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:8m:46m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;

   echo "LOADING MODULES"   
   fp_control -t "LOADING MODULES"

   if [ ! -e /boot/audio.elf ]; then
      fp_control -t "FW MISSING!!!"
   fi

   echo "load a firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko type=stv6417

   player=`cat /proc/stb/player/version`
   if [ $player=='player191' ]; then
      echo "init player 191"
   elif [ $player=='player179' ]; then
      echo "init player 179"
   else
      echo "init player 131"
   fi
   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/pseudocard.ko
   insmod $MODDIR/cec_ctrl.ko

    if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
         echo "init frontends bialy"
         insmod $MODDIR/fe-core.ko
    elif [ $boxtype == 'bsla' ]; then
         echo "init frontends czarny"
	 insmod $MODDIR/fe-core-twin1.ko
    else
	 insmod $MODDIR/fe-core-twin2.ko
    fi

   echo "init drivers"
   if [ $player -gt 131 ]; then
	insmod $MODDIR/pti.ko
	insmod $MODDIR/stm_monitor.ko
	insmod $MODDIR/stmsysfs.ko
	if [ $boxtype == 'bzzb' ]; then
	  insmod $MODDIR/stmdvb.ko TSIS_mode=serial ;
	else
	  insmod $MODDIR/stmdvb.ko TSIS_mode=parallel ;
	fi
   else
	insmod $MODDIR/pti.ko
	insmod $MODDIR/stmdvb.ko
	insmod $MODDIR/stm_monitor.ko
   fi	
   insmod $MODDIR/player2.ko discardlateframe=0
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/smartcard.ko
   insmod $MODDIR/bpamem.ko

   echo "init frontpanel"
   insmod $MODDIR/simu_button.ko

   echo "init lircd"
   mkdir -p /var/run/lirc
   /usr/bin/lircd

   /bin/evremote2 &

   /etc/init.d/mountall start

   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   /etc/init.d/network start &

   (until false; do echo 1 > /proc/sys/vm/drop_caches; sleep 2; done) &

   echo "LOADING xbmc" > /dev/vfd
   echo "LOADING xbmc"

   /etc/init.d/xbmc_userdata

   stfbcontrol a 255

   until false
   do
      echo "starting xbmc->"
      /usr/lib/xbmc/xbmc.bin
      rtv=$?
      echo "xbmc ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo " ERROR"
      	   init 6;;
		1) echo "1"
		   echo "SHUTDOWN"
		   init 0;;
		2) echo "2"
		   echo "REBOOT"
		   init 6;;
		*) echo "*"
		   echo "ERROR"
           init 6;;
      esac
   done 
fi

#never reached

