#!/bin/sh

MODDIR=/lib/modules

echo fortis hdbox

insmod $MODDIR/nuvoton.ko

if [ -e /var/etc/.firstboot ]; then
   echo "WAIT 1 min" > /dev/vfd
   echo "WAIT 1 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start

insmod $MODDIR/e2_proc.ko

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/login

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-stx7109c3.ko
   insmod $MODDIR/stmfb.ko display0=1280x720-32@60:12m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;

   echo "LOADING MODULES"   
   echo "LOADING MODULES" >/dev/vfd

   echo "load a/v firmware"
   /bin/stslave -t stb7100.0 -R /boot/video.elf
   /bin/stslave -t stb7100.1 -R /boot/audio.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko type=stv6412

   echo "init player"
   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER1;
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/pseudocard.ko

   insmod $MODDIR/stv090x.ko
   insmod $MODDIR/cimax.ko
   insmod $MODDIR/pti.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/player2.ko
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   showiframe -p /boot/bootlogo.mvi &
   stfbcontrol a 0

   echo "init frontpanel"
   insmod $MODDIR/boxtype.ko
   insmod $MODDIR/simu_button.ko

   mknod /dev/rc c 147 1 

   #params:
   #period
   #delay
   /bin/evremote2 10 140 &

   #DVD-PLAYER EXIT-TASTE LOAD OR EJECT DVD
   #mount /dev/sr0 /media/dvd
   #fix this later if we got to manage a marusys raw device driver
#   mount /dev/sda5 /hdd/

   /etc/init.d/portmap start
   /etc/init.d/vsftpd start
   /usr/sbin/inetd
   #timefix e2
   date -s "121220001970"
   # custom script
   if [ -e /var/etc/rcS_local ]; then
	/var/etc/rcS_local
   fi
   # downmix workaround
    if [ -e  /var/etc/.downmix ]; then
	echo downmix > /proc/stb/audio/ac3
	echo downmix > /proc/stb/audio/ac3_choice
    fi
   
   stfbcontrol a 255

   echo "Load Neutrino" > /dev/vfd
   echo "Load Neutrino"

until false
do
 killall -9 showiframe
 echo "starting neutrino ->"
 /usr/local/bin/neutrino
     rtv=$?
      echo "neutrino ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "ERROR"
      	   init 6;;
		1) echo "1"
		   echo "SHUTDOWN"
		   init 0;;
		2) echo "2"
		   echo "REBOOT"
		   init 6;;
		3) echo "3"
		   echo "RESTART"
		   echo "0" > /proc/progress
		   showiframe -p /boot/bootlogo.mvi &;;
		*) echo "*"
		   echo "ERROR"
           init 6;;
      esac
   done 
fi

#never reached
echo "REBOOT HDBOX" > /dev/vfd
echo "REBOOT HDBOX"
init 6