#!/bin/sh
#set -x

MODDIR=/lib/modules
insmod $MODDIR/micom.ko

if [ -e /var/etc/.firstboot ]; then
   #fp_control does not work here
   echo "WAIT 1 min" > /dev/vfd
   echo "WAIT 1 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start

/etc/init.d/portmap start

   insmod $MODDIR/e2_proc.ko

# start automounter with umount timeout of 5 seconds
/usr/sbin/automount --timeout=5 /autofs file /etc/auto.usb

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   fp_control -c

   #green led on
   fp_control -l 2 1
   #led brightness
   fp_control -led 80

   echo "starting telnetd"
   fp_control -t "starting telnetd"
   /usr/sbin/telnetd -l /bin/login

   echo "starting oscam"
   fp_control -t "starting oscam"
   /var/emu/oscam -b -c /var/keys/

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-sti7111.ko
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:15m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;

   echo "LOADING MODULES"   
   fp_control -t "LOADING MODULES"

   if [ ! -e /boot/audio.elf ]; then
      fp_control -t "FW MISSING!!!"
   fi

   echo "load a/v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf
   /bin/ustslave /dev/st231-1 /boot/audio.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko type=stv6417

   echo "init player"
   insmod $MODDIR/mmelog.ko
   #there is no mpeg2hw on ufs912, will be handled by fw & copos
   #insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0;
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/pseudocard.ko

   insmod $MODDIR/stv090x.ko
   insmod $MODDIR/ufs912_cic.ko
   insmod $MODDIR/pti.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/player2.ko
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko

   insmod $MODDIR/bpamem.ko
   mknod /dev/bpamem c 153 0 

   #showiframe -p /boot/bootlogo.mvi &
   #stfbcontrol a 0

   echo "init frontpanel"
   insmod $MODDIR/simu_button.ko

   mknod /dev/rc c 147 1 

   #params:
   #period
   #delay
   /bin/evremote2 10 120 &

   #timefix
#   date -s "121220002010"
#   date -s "2011-12-12 12:00"
   cp -P /etc/localtime /tmp/TZ
   ntpd -nqp 0.de.pool.ntp.org

   #stfbcontrol a 255

   fp_control -t "LOADING vdr"
   echo "LOADING vdr"

   /etc/init.d/mountall start

   #DVD-PLAYER EXIT-TASTE LOAD OR EJECT DVD
   #mount /dev/sr0 /media/dvd
#   mount -t ext3 /dev/sda1 /hdd/movie
#   mount -t ext3 /dev/sda1 /media/video
   mount -t ext3 /dev/sdb1 /media/video

   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/login
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   NFS=$(grep -c 'nfs' /proc/cmdline)
   if [ "$NFS" -eq "1" ]; then 
      echo "Booting from nfs, don't set network" 
   else 
      if [ -e /etc/network/interfaces ]; then 
	 ip addr flush eth0 
	 /etc/init.d/networking stop 
	 TEST=$(grep -c 'dhcp' /etc/network/interfaces) 
	 if [ "$(TEST)" -eq "1" ]; then 
	    echo dhcp
            /etc/init.d/udhcpc start 
	 fi 
	 /etc/init.d/networking start 
      fi 
   fi

#   echo 720p50 >/proc/stb/video/videomode
#   echo "bestfit" > /proc/stb/video/policy

   # start vdr run script
   # for plugin configuration see: /var/vdr/plugins.load
   /usr/local/bin/runvdr &

   # exit now from here,
   # all further processing is done in runvdr script, to free memory of rcS
   exit
fi


#never reached
echo "REBOOT UFS912" > /dev/vfd
echo "REBOOT UFS912"
reboot
