#!/bin/sh

MODDIR=/lib/modules
echo "init frontpanel"
insmod $MODDIR/aotom.ko
insmod $MODDIR/simu_button.ko
insmod $MODDIR/encrypt.ko

ifconfig eth0 up
udhcpc &

busybox bash &

if [ -e /var/etc/.firstboot ]; then
   echo "WAIT 1 min" >/dev/vfd
   echo "WAIT 1 min"
   mknod -m 622 /dev/console c 5 1
   mknod -m 666 /dev/null c 1 3
   mknod -m 666 /dev/zero c 1 5
   mknod -m 666 /dev/ptmx c 5 2
   mknod -m 666 /dev/tty c 5 0
   mknod -m 444 /dev/random c 1 8
   mknod -m 444 /dev/urandom c 1 9
   chown -v root:tty /dev/{console,ptmx,tty}
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start
/etc/init.d/portmap start

insmod $MODDIR/e2_proc.ko

/etc/init.d/autofs start

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-sti7105.ko
   insmod $MODDIR/stmfb.ko display0=1920x1080-32@60:12m:24m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;

   echo "LOADING MODULES"   
   echo "LOAD" > /dev/vfd

   if [ ! -e /boot/audio.elf ]; then
      echo "FW MISSING!!!"
   fi

   echo "load a firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
   insmod $MODDIR/mme_host.ko transport0=shm

   #insmod $MODDIR/embxmailbox.ko mailbox0=0xFE211000:136:set2 mailbox1=0xFE212000:137:set2
   #insmod $MODDIR/embxshm.ko mailbox0=TransportVideo0:0:3:0x00000000:0:16:16:0:256:0x40000000:0x40000000 mailbox1=TransportAudio1:0:5:0x00000000:0:16:16:0:256:0x40000000:0x40000000
   #insmod $MODDIR/mme_host.ko transport0=TransportVideo0 transport1=TransportAudio1*/

   echo "init AVS"
   insmod $MODDIR/avs.ko type=avs_pio

   player=`cat /proc/stb/player/version`
   player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
   echo "init player $player"

   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   if [ $player -gt 131 ]; then
      insmod $MODDIR/stmvout.ko
      insmod $MODDIR/stmvbi.ko
   fi
   insmod $MODDIR/pseudocard.ko

   #you can change t to c to switch the tuner type
   insmod $MODDIR/spark7162.ko UnionTunerType=t
   if [ $player -gt 131 ]; then
      # Full feature pti
      insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
      if [ $?=='2' ]; then
         # Simple pti
         insmod $MODDIR/pti.ko
      fi
      insmod $MODDIR/stm_monitor.ko
      insmod $MODDIR/stmsysfs.ko
      insmod $MODDIR/stmdvb.ko
   else
      insmod $MODDIR/pti.ko
      insmod $MODDIR/stmdvb.ko
      insmod $MODDIR/stm_monitor.ko
   fi
   insmod $MODDIR/player2.ko
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko
   insmod $MODDIR/smartcard.ko
   insmod $MODDIR/cec.ko activemode=1

   insmod $MODDIR/bpamem.ko
   mknod /dev/bpamem c 153 0 

   echo "init lircd"
   /usr/bin/lircd

   mknod /dev/rc c 147 1 
   mknod /dev/sci0 c 169 0
   mknod /dev/sci1 c 169 1 
   major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
   rm -f /dev/sparkid
   mknod /dev/sparkid c $major 0 

   /bin/evremote2 10 100 &

   stfbcontrol a 255

   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   /etc/init.d/network start &
   (until false; do echo 1 > /proc/sys/vm/drop_caches; sleep 2; done) &
	mknod /dev/dvb/adapter0/frontend1 c 212 19
	mknod /dev/dvb/adapter0/frontend2 c 212 35
	mknod /dev/dvb/adapter0/frontend3 c 212 51
	
   NFS=`grep -c nfs /proc/cmdline`
   if [ "$NFS" -eq "1" ]; then 
      echo "Booting from nfs, don't set network" 
   else 
      if [ -e /etc/network/interfaces ]; then 
	 ip addr flush eth0 
	 /etc/init.d/networking stop 
	 DHCP=`grep -c dhcp /etc/network/interfaces`
	 if [ "$DHCP" -eq "1" ]; then 
	    echo "Starting dhcp"
            /etc/init.d/udhcpc start 
	 fi 
	 /etc/init.d/networking start 
      fi 
   fi

   echo "LOADING xbmc" > /dev/vfd
   echo "LOADING xbmc"

   /etc/init.d/xbmc_userdata
/usr/lib/xbmc/xbmc.bin 

   
fi

#never reached
