#!/bin/sh

MODDIR=/lib/modules
insmod $MODDIR/micom.ko

if [ -e /var/etc/.firstboot ]; then
   #fp_control does not work here
   echo "WAIT 1 min" >/dev/vfd
   echo "WAIT 1 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start

insmod $MODDIR/e2_proc.ko

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   fp_control -c

   #green led on
   fp_control -l 2 1
   #led brightness
   fp_control -led 80

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/login

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-sti7111.ko
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;

   echo "LOADING MODULES"   
   fp_control -t "LOADING MODULES"

   echo "load a firmware"
   /bin/ustslave_stm23 /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave_stm23 /dev/st231-0 /boot/video.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko type=stv6417

   echo "init player"
   insmod $MODDIR/mmelog.ko
   #there is no mpeg2hw on ufs912, will be handled by fw & copos
   #insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0;
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/pseudocard.ko

   insmod $MODDIR/stv090x.ko
   insmod $MODDIR/ufs912_cic.ko
   insmod $MODDIR/pti.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/player2.ko
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko

   #showiframe -p /boot/bootlogo.mvi &
   #stfbcontrol a 0

   echo "init frontpanel"
   insmod $MODDIR/simu_button.ko

   mknod /dev/rc c 147 1 

   #toggleFeedback 0 = false, 1 = true
   #maxRate (same key) = 2, maxDelay (determine new key) = 500
   /bin/evremote2 1 2 500 &

   /etc/init.d/portmap start
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   #timefix e2
   date -s "121220001970"

   #stfbcontrol a 255

   fp_control -t "LOADING neutrino"
   echo "LOADING neutrino"

   insmod $MODDIR/clk.ko

   until false
   do
      echo "starting neutrino ->"
      /usr/local/bin/neutrino -f -u
      rtv=$?
      echo "neutrino ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "SHUTDOWN"
		   sync
		   umount -a -l -f;;
		1) echo "1"
		   echo "SHUTDOWN"
		   sync

                   #green green off
                   fp_control -l 2 0

                   #green red on
                   fp_control -l 3 1
                   
		   #led brightness
                   fp_control -led 5

		   fp_control -e
		   umount -a -l -f;;
		2) echo "2"
		   echo "BOX RESTART"
		   reboot -f;;
		*) echo "*"
		   echo "Unexpected error"
                   reboot;;
      esac
   done 
fi

#never reached
echo "REBOOT UFS912" > /dev/vfd
echo "REBOOT UFS912"
reboot
