#!/bin/sh

MODDIR=/lib/modules

insmod $MODDIR/vfd.ko
insmod $MODDIR/aotom.ko

if [ -e /var/etc/.firstboot ]; then
   echo "WAIT 1 min" >/dev/vfd
   echo "WAIT 1 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

echo "mount" > /dev/vfd

/etc/init.d/mountvirtfs start

/etc/init.d/portmap start

#echo "starting telnetd"
#/usr/sbin/telnetd -l /bin/login
insmod $MODDIR/e2_proc.ko

# start automounter with umount timeout of 5 seconds
#/usr/sbin/automount --timeout=5 /autofs file /etc/auto.usb

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/login

   insmod $MODDIR/simu_button.ko

   echo "init lircd"
   /usr/bin/lircd

   /bin/evremote2 spark &
 
   echo "init stmfb"
   insmod $MODDIR/stmcore-display-sti7111.ko
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:10m:pal:yuv:yuv #display1=720x576-16@50:3m:pal:cvbs;

   echo "LOADING MODULES"   
   echo "LOADING MODULES" > /dev/vfd

   if [ -e /boot/audio.elf ]; then
	  echo "load a firmware"
   else
       echo "FW MISSING!!!"
   fi

   echo "load a firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko type=spark_avs #type=stv6417

   player=`cat /proc/stb/player/version`
   if [ $player=='player179' ]; then
	echo "[rcS] init player 179"
   else
	echo "[rcS] init player 131"
   fi
   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   if [ $player=='player179' ]; then
	insmod $MODDIR/stmvout.ko
	insmod $MODDIR/stmvbi.ko
   fi
   insmod $MODDIR/pseudocard.ko

   insmod $MODDIR/stv090x.ko
   if [ $player=='player179' ]; then
	insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
	insmod $MODDIR/stm_monitor.ko
	insmod $MODDIR/stmsysfs.ko
    insmod $MODDIR/stmdvb.ko highSR=1 swts=1
   else
	insmod $MODDIR/pti.ko
    insmod $MODDIR/stmdvb.ko
	insmod $MODDIR/stm_monitor.ko
   fi	
   insmod $MODDIR/player2.ko
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko

   showiframe -p /boot/bootlogo.mvi &
   stfbcontrol a 0

   echo "init frontpanel"


   mknod /dev/rc c 147 1 

   #toggleFeedback 0 = false, 1 = true
   #maxRate (same key) = 2, maxDelay (determine new key) = 500
   #/bin/evremote2 1 2 500 &

   # timefix e2
   # date -s "121220001970"

   stfbcontrol a 255

   echo "LOADING E2"

   /etc/init.d/mountall start

   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/login
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   until false
   do
      echo "starting e2->"
      /usr/local/bin/enigma2
      rtv=$?
      echo "e2 ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "E2 ERROR"
      		   reboot;;
		1) echo "1"
		   echo "SHUTDOWN"
                   sync
                   umount -a;;
		2) echo "2"
		   echo "REBOOT"
		   reboot;;
		3) echo "3"
		   echo "E2 RESTART"
		   echo "0" > /proc/progress
		   showiframe -p /boot/bootlogo.mvi &;;
		*) echo "*"
		   echo "ERROR"
                   reboot;;
      esac
   done 
fi

#never reached
echo "REBOOT SPARK" > /dev/vfd
echo "REBOOT SPARK"
reboot
