#!/bin/sh

MODDIR=/lib/modules

loadMME() {
   # mme bug workaround
   /bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
   /bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
   # end mme bug wa
   echo "load a firmware"
   /bin/stslave -t stb7100.1 -R /boot/audio.elf
   echo "load v firmware"
   /bin/stslave -t stb7100.0 -R /boot/video.elf
}

if [ -e /var/etc/.firstboot ]; then
   insmod $MODDIR/vfd.ko
   echo "WAIT 1 min" > /dev/vfd
   echo "WAIT 1 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start

if [ ! -e /var/etc/.firstboot ]; then

   insmod $MODDIR/e2_proc.ko

   loadMME

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/login


   echo "LOADING MODULES"   
   fp_control -c
   
   echo "init embxshell"
   insmod $MODDIR/embxshell.ko
   echo "init embxmailbox"
   insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:137:set2 ;
   echo "init embxshm"
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0xa4000000:0x10000000 ;

   echo "init mme_host"
   touch /etc/mme.tmp
   echo "interupts pre"
   echo $(cat /proc/interrupts | grep mailbox)
   /etc/init.d/mme_check &
   insmod $MODDIR/mme_host.ko transport0=shm &
   echo "interupts aft"
   echo $(cat /proc/interrupts | grep mailbox)
   rm /etc/mme.tmp

   insmod $MODDIR/vfd.ko       
   echo "    Welcome     " > /dev/vfd
   echo "MME LOADED"

   echo "init AVS"
   insmod $MODDIR/avs.ko

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-stx7100.ko
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;

   echo "init player"
   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0;
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/pseudocard.ko
   insmod $MODDIR/cx24116.ko
   insmod $MODDIR/cimax.ko
   insmod $MODDIR/pti.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/player2.ko
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko

   #showiframe -p /boot/bootlogo.mvi &
   #stfbcontrol a 0

   echo "init lircd"
   /usr/bin/lircd

   echo "init frontpanel"
   insmod $MODDIR/boxtype.ko
   insmod $MODDIR/simu_button.ko
   /bin/evremote2 &
   var=`cat /proc/boxtype`
   case "$var" in
   	0) echo "1W boxtype"
	   echo "B" > /dev/ttyAS1
           echo "B" > /dev/ttyAS1;;
  	1|3) echo "14W boxtype"
      	   insmod $MODDIR/button.ko
      	   insmod $MODDIR/led.ko;;
   	*) echo "unknown boxtype";;
   esac

   #DVD-PLAYER EXIT-TASTE LOAD OR EJECT DVD
   #mount /dev/sr0 /media/dvd
   mount -t ext3 /dev/sda1 /hdd/movie

   /etc/init.d/portmap start
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   #timefix e2
   date -s "121220001970"

   stfbcontrol a 255

   echo "LOADING neutrino" > /dev/vfd
   echo "LOADING neutrino"

   until false
   do
      echo "starting neutrino ->"
      /usr/local/bin/neutrino -f -u
      rtv=$?
      echo "neutrino ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "SHUTDOWN"
		   case "$var" in
			0) fp_control -e
                           umount -a;;
  			1|3) fp_control -e #please check if this works for ufs910 14W
                             echo "0" > /proc/progress
		             showiframe -p /boot/bootlogo.mvi &;;
		   esac;; 
		1) echo "1"
		   echo "SHUTDOWN"
		   case "$var" in
			0) fp_control -e
                           umount -a;;
  			1|3) fp_control -e #please check if this works for ufs910 14W
                             echo "0" > /proc/progress
		             showiframe -p /boot/bootlogo.mvi &;;
		   esac;; 
		2) echo "0"
		   echo "Box restart"
      		   reboot -f;;          
		*) echo "*"
		   echo "Unexpected error"
                   reboot;;
      esac
   done 
fi

#never reached
echo "REBOOT UFS910" > /dev/vfd
echo "REBOOT UFS910"
reboot
