#!/bin/sh


/sbin/ifconfig lo 127.0.0.1
/bin/hostname $HOSTNAME

echo "Mount usb /dev/sda1"
mount /dev/sda1 /mnt
if [ ! -d /mnt/kathrein/ufs913 ]; then
  echo "ERROR: NO UPDATEFOLDER ON USB"
  exit 0
fi

echo "Check fw"
if [ -e /mnt/kathrein/ufs913/mtd_fw.sum.bin ]; then
  echo "Write fw"
  dd if=/mnt/kathrein/ufs913/mtd_fw.sum.bin of=/dev/mtd8
fi

echo "Check rootfs"
if [ -e /mnt/kathrein/ufs913/mtd_root.sum.bin ]; then
  echo "Write fw"
  dd if=/mnt/kathrein/ufs913/mtd_root.sum.bin of=/dev/mtdblock9
fi

echo "Check fw"
if [ -e /mnt/kathrein/ufs913/uImage ]; then
  echo "Write fw"
  dd if=/mnt/kathrein/ufs913/uImage of=/dev/mtdblock6
fi

echo "Reboot"
reboot -f
