#!/bin/sh

/bin/update &

/sbin/ifconfig lo 127.0.0.1
/bin/hostname $HOSTNAME

sleep 4

echo "Mount usb /dev/sda1"
mount /dev/sda1 /mnt
if [ ! -d /mnt/kathrein/ufs913 ]; then
  echo "ERROR: NO UPDATEFOLDER ON USB"
  killall update
  /bin/update ERR_USB &
  exit 0
fi

echo "Check fw"
if [ -e /mnt/kathrein/ufs913/mtd_fw.sum.bin ]; then
  echo "Write fw"
  flash_eraseall -j /dev/mtd8
  dd of=/dev/mtdblock8 if=/mnt/kathrein/ufs913/mtd_fw.sum.bin
fi

echo "Check rootfs"
if [ -e /mnt/kathrein/ufs913/mtd_root.sum.bin ]; then
  echo "Write fw"
  flash_eraseall -j /dev/mtd9
  dd of=/dev/mtdblock9 if=/mnt/kathrein/ufs913/mtd_root.sum.bin
fi

echo "Check fw"
if [ -e /mnt/kathrein/ufs913/uImage.bin ]; then
  echo "Write fw"
  dd if=/mnt/kathrein/ufs913/uImage.bin of=/dev/mtdblock6
fi

echo "Reboot"
reboot -f
