#! /bin/sh
#
# rcS		Call all S??* scripts in /etc/rcS.d in
#		numerical/alphabetical order.
#
# Version:	@(#)/etc/init.d/rcS  2.76  19-Apr-1999  miquels@cistron.nl
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#
# Source splash functions
#
. /lib/lsb/splash-functions

#
#	See if system needs to be setup. This is ONLY meant to
#	be used for the initial setup after a fresh installation!
#
if [ -x /sbin/unconfigured.sh ]
then
  /sbin/unconfigured.sh
fi

#
#	Source defaults.
#
. /etc/default/rcS
export VERBOSE

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
trap ":" INT QUIT TSTP

mount none /proc -t proc
mount none /sys  -t sysfs
mount tmpfs /lib/splash/cache -t tmpfs

#
# STMFB
#
#kernel command line:
#w/ CONFIG_FB_SPLASH: splash=silent console=ttyAS0,115200
#w/ CONFIG_FB_CON_DECOR: splash=off console=ttyAS0,115200 (silent)
#w/ CONFIG_FB_CON_DECOR: splash=verbose console=ttyX (toggle between verbose and silent)
modprobe avs
modprobe stmcore-display-stx7100
modprobe stmfb display0=720x576-16@50:10m:pal:yuv:yuv #display1=720x576-16@50:1m:pal:cvbs;

#
# frontpanel modules
#
modprobe vfd
modprobe boxtype

var=`cat /proc/boxtype`
case "$var" in
	0) echo "1W boxtype"
	   /bin/stty -F /dev/ttyAS1 speed 19200
	   /bin/stty -F /dev/ttyAS1 -icrnl
	   /bin/stty -F /dev/ttyAS1 -onlcr
	   /bin/stty -F /dev/ttyAS1 -echo
	   /bin/stty -F /dev/ttyAS1 -iexten
	   echo B > /dev/ttyAS1;;
	1|3) echo "14W boxtype"
	   modprobe button
	   modprobe led;;
	*) echo "unknown boxtype";;
esac

#
# SPLASHSCREEN
#
if grep -q splash /proc/cmdline; then
	verbose=`grep -c verbose /proc/cmdline`
	max_progress=`ls /etc/rc.d/rcS.d/S* | wc -l`
	k=`expr 32767 / $max_progress`
	j=$k
	if [ $verbose -eq 0 ]; then
		fbsplashd --effects=fadein --type=bootup --pidfile=/lib/splash/cache/splash.pid
		echo "set mode silent">/lib/splash/cache/.splash
		#echo "set event dev /dev/input/event0">/lib/splash/cache/.splash
	else
		fbsplashd.static.BTN_01 --pidfile=/lib/splash/cache/splash.pid
		echo "set event dev /dev/input/event0">/lib/splash/cache/.splash
	fi
fi

#
#	Call all parts in order.
#
echo "Running level S" >/dev/vfd

for i in /etc/rc.d/rcS.d/S[0-9]?*
do
	# Ignore dangling symlinks for now.
	[ ! -f "$i" ] && continue

	case "$i" in
		*.sh)
			splash_message $i
			# Source shell script for speed.
			(
				trap - INT QUIT TSTP
				set start
				. $i
			)
			;;
		*)
			# No sh extension, so fork subprocess.
			splash_message $i
			$i start
			;;
	esac
	splash_progress
done

#
#	Finish setup if needed. The comment above about
#	/sbin/unconfigured.sh applies here as well!
#
if [ -x /sbin/setup.sh ]
then
  /sbin/setup.sh
fi
