#!/bin/sh
#
# ufs910-common	
#
# chkconfig: 3 11 0
# description: 
#
# pidfile: 

PATH=/sbin:/bin:/usr/bin:/usr/sbin
NAME=ufs910-common
DESC="UFS910 Common Services"

RETVAL=0

# Set environment values (see /etc/default/ufs910)
APP_PATH=/dev/mtdblock4
CONFIG_PATH=/dev/mtdblock2
DATA_PATH=/dev/mtdblock6
APP_OVERLAY=no
[ -f /etc/default/ufs910-common ] && . /etc/default/ufs910-common

mount_path() {
	( grep -q "$1" /proc/mounts ) && umount $1
	[ -h $1 ] && rm $1
	[ ! -d $1 ] && mkdir $1
	mount -t $3 $2 $1 >/dev/null 2>&1
}

start(){
	echo -n "Starting $DESC: "

	mount_path /config $CONFIG_PATH jffs2

	if ( grep -q "/dev/mtdblock3 /var jffs2" /proc/mounts ); then
		mount --bind /var /data
	else
		mount_path /data $DATA_PATH jffs2
	fi

	echo "$NAME."
	
#	mount_path /app $APP_PATH cramfs || mount_path /app $APP_PATH squashfs
#	if [ "x$APP_OVERLAY" = "xyes" ]; then
#		[ ! -d /data/app ] && mkdir -p /data/app
#		[ ! -d /data/app.static ] && mkdir -p /data/app.static
#		mount -o bind /app /data/app.static
#		mount -t mini_fo -o base=/data/app.static,sto=/data/app /data/app.static /app
#	fi
	if [ "x$APP_OVERLAY" = "xyes" ]; then
		[ ! -d /data/app ] && mkdir -p /data/app
		mount_path /app.static $APP_PATH cramfs || mount_path /app.static $APP_PATH squashfs
		mount -t mini_fo -o base=/app.static,sto=/data/app /app.static /app
	else
		mount_path /app $APP_PATH cramfs || mount_path /app $APP_PATH squashfs
	fi


	# Create/Mount directories
	[ ! -d /var/CI ] && mkdir /var/CI
	grep -q "tmpfs /var tmpfs" /proc/mounts || mount -t tmpfs tmpfs /var/CI
	mount -t tmpfs tmpfs /ramdisk

	RETVAL=$?
}

stop(){
    echo -n "Stopping $DESC: "

    RETVAL=$?
    echo "$NAME."

}

reload(){
    echo -n $"Reloading configuration: "	

    RETVAL=$?
    echo
}

restart(){
    stop
    start
}

# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    reload)
	reload
	;;
    *)
	echo $"Usage: $0 {start|stop|restart|reload}"
	RETVAL=1
esac
exit $RETVAL
