#!/bin/sh

NEUTRINO="NO" #Is set below
ENIGMA2="NO" #Is set below
VDR="NO" #Is set below

PLAYER="player191" #Is set below
CPU="STx7100" #Is set below

STM="stm24" #Is set below

MODDIR=/lib/modules

mount -a

if [ -ne /etc/.devfs ]; then
	mount -t tmpfs -o size=64k,mode=0755 mdev /dev
	touch /dev/.udev
	mkdir /dev/pts
	mount -t devpts devpts /dev/pts
	echo /sbin/mdev > /proc/sys/kernel/hotplug
	/sbin/mdev -s
else
	mount -t tmpfs tmpfs /ram
	cp -a /dev /ram
	mount --bind /dev /dev.static
	mount --bind /ram /dev
	touch /dev/.devfs
fi

CPU=`cat /proc/cpuinfo | grep "cpu type" | sed "s/cpu type\t: //g" | sed "s/i/x/g"` | sed "s/b/x/g"`
#STx7105, STx7111, STx7100, STx7101, STx7109

if [ `cat /proc/version | grep -c "stm23"` -eq "1" ]; then
   STM="stm23"
elif [ `cat /proc/version | grep -c "stm24"` -eq "1" ]; then
   STM="stm24"
fi

. /etc/init.d/vfd.sh

initVFD $MODDIR
echoVFD "DUCKBOX"

/etc/init.d/mountall start

if [ -e /usr/local/bin/neutrino ]; then
   NEUTRINO="YES"
elif [ -e /usr/local/bin/enigma2 ]; then
   ENIGMA2="YES"
else
   VDR="YES"
fi

insmod $MODDIR/e2_proc.ko

PLAYER=`cat /proc/stb/player/version`
#player179, player191

echo "starting network services"
/etc/init.d/hostname start

NFS=$(grep -c 'nfs' /proc/cmdline)
if [ "$NFS" -eq "1" ]; then
   echo "Booting from nfs, don't set network"
elif [ -e /etc/network/interfaces ]; then
   ip addr flush eth0
   /etc/init.d/networking stop
   TEST=$(grep -c 'dhcp' /etc/network/interfaces)
   if [ "$(TEST)" -eq "1" ]; then 
      echo "DHCP"
      /etc/init.d/udhcpc start
   fi 
   /etc/init.d/networking start
fi

echo "starting telnetd services"
/usr/sbin/telnetd -l /bin/login

echo "starting other network services"
/etc/init.d/portmap start
/etc/init.d/vsftpd start
/usr/sbin/inetd

. /etc/init.d/init_box_pre.sh $MODDIR

/bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
/bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
echo "load a firmware"
/bin/ustslave /dev/st231-1 /boot/audio.elf
echo "load v firmware"
/bin/ustslave /dev/st231-0 /boot/video.elf

echo "init embx drivers"
insmod $MODDIR/embxshell.ko
if [ $CPU -eq "STx7100" -o $CPU -eq "STx7101" -o $CPU -eq "STx7109" ]; then
   insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:137:set2 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0xa4000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm
else
   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm
fi

echo "init stmfb drivers"
insmod $MODDIR/stmcore-display-stx7100.ko
if [ $NEUTRINO -eq "YES" ]; then
   # 8mb is sufficient For Neutrino
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:8m:pal:yuv:yuv;
else
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv;
fi

echo "init player drivers"
insmod $MODDIR/mmelog.ko
if [ $CPU -eq "STx7100" -o $CPU -eq "STx7101" -o $CPU -eq "STx7109" ]; then
   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0;
fi
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stm_v4l2.ko
insmod $MODDIR/stmvout.ko
insmod $MODDIR/stmvbi.ko
insmod $MODDIR/pseudocard.ko

if [ $PLAYER -eq 'player179' ]; then
   insmod $MODDIR/pti.ko $PTI_P179_ARGS
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/stmsysfs.ko
   insmod $MODDIR/stmdvb.ko $STMDVB_P179_ARGS
elif
   insmod $MODDIR/pti.ko $PTI_P191_ARGS
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/stmsysfs.ko
   insmod $MODDIR/stmdvb.ko $STMDVB_P191_ARGS
fi
insmod $MODDIR/player2.ko
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko
insmod $MODDIR/silencegen.ko

echo "init other drivers"
insmod $MODDIR/bpamem.ko

if [ $ENIGMA2 -eq "YES" ]; then
   showiframe -p /boot/bootlogo.mvi &
fi

. /etc/init.d/init_box_post.sh $MODDIR

stfbcontrol a 255
