#!/bin/sh

MODDIR=/lib/modules

rm /var/etc/.firstboot

mount -t tmpfs -o size=64k,mode=0755 mdev /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mount -t proc proc /proc
mount -t sysfs sysfs /sys
echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s

touch /dev/.udev

. /etc/init.d/init_vfd.sh $MODDIR

if [ ! -e /var/etc/.firstboot ]; then

   insmod $MODDIR/e2_proc.ko

   /bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
   /bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
   echo "load a firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/login

   . /etc/init.d/init_box.sh $MODDIR
   
   echo "init embxshell"
   insmod $MODDIR/embxshell.ko
   echo "init embxmailbox"
   insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:137:set2 ;
   echo "init embxshm"
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0xa4000000:0x10000000 ;
   echo "init mme_host"
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-stx7100.ko
   if [ -e /usr/local/bin/neutrino ]; then
      # 8mb is sufficient for Neutrino
      insmod $MODDIR/stmfb.ko display0=1280x720-32@50:8m:pal:yuv:yuv;
   else
      insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv;
   fi

   echo "init player"
   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0;
   insmod $MODDIR/stmsysfs.ko
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/pseudocard.ko
   insmod $MODDIR/pti.ko
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/player2.ko
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko
   insmod $MODDIR/bpamem.ko

   echo "init lircd"
   /usr/bin/lircd

   echo "init frontpanel"
   /bin/evremote2 &

   /etc/init.d/portmap start
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   # timefix
   date -s "121220001970"

   echo "LOADING" > $VFD
   echo "LOADING"

   if [ ! -e /usr/local/bin/neutrino ]; then
      showiframe -p /boot/bootlogo.mvi &
   fi

   stfbcontrol a 255
   until false
   do
      echo "starting ->"
      if [ -e /usr/local/bin/neutrino ]; then
         /usr/local/bin/neutrino -f -u
      else
         /usr/local/bin/enigma2
      fi

      echo "ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "ERROR"
      	   init 6;;
		1) echo "1"
		   echo "SHUTDOWN"
		   init 0;;
		2) echo "2"
		   echo "REBOOT"
		   init 6;;
		3) echo "3"
		   echo "RESTART"
		   echo "0" > /proc/progress
		   showiframe -p /boot/bootlogo.mvi &;;
		*) echo "*"
		   echo "ERROR"
           init 6;;
      esac
   done 
fi

echo "REBOOT" > $VFD
echo "REBOOT"
reboot
